### ISSUE TITLE
Error: No dependency factory available for this dependency type: MultiEntryDependency

### ISSUE THREAD

**Issue by MaxmaxmaximusGitHub** [JoviDeCroock/preact-refresh#6]
```cmd
> csgo@1.0.0 dev C:\localhost\csgo
> cross-env NODE_OPTIONS='--inspect' next

Debugger listening on ws://127.0.0.1:9229/09daed7d-7fde-432b-b57f-f9776fcecd38
For help, see: https://nodejs.org/en/docs/inspector
[ wait ]  starting the development server ...
[ info ]  waiting on http://localhost:3000 ...
[ ready ] compiled successfully - ready on http://localhost:3000
[ event ] build page: /next/dist/pages/_error
[ wait ]  compiling ...
Error: No dependency factory available for this dependency type: MultiEntryDependency
    at Compilation._addModuleChain (C:\localhost\csgo\node_modules\webpack\lib\Compilation.js:1057:10)
    at Compilation.addEntry (C:\localhost\csgo\node_modules\webpack\lib\Compilation.js:1164:8)
    at C:\localhost\csgo\node_modules\next\dist\server\on-demand-entry-handler.js:2:168
    at new Promise (<anonymous>)
    at addEntry (C:\localhost\csgo\node_modules\next\dist\server\on-demand-entry-handler.js:2:58)
    at C:\localhost\csgo\node_modules\next\dist\server\on-demand-entry-handler.js:3:129
    at async Promise.all (index 0)
(node:3676) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'addChunk' of null
    at Object.connectChunkAndModule (C:\localhost\csgo\node_modules\webpack\lib\GraphHelpers.js:35:13)
    at Compilation.seal (C:\localhost\csgo\node_modules\webpack\lib\Compilation.js:1308:17)
    at C:\localhost\csgo\node_modules\webpack\lib\Compiler.js:675:18
    at C:\localhost\csgo\node_modules\webpack\lib\Compilation.js:1261:4
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\localhost\csgo\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonym
ous>:13:1)
    at AsyncSeriesHook.lazyCompileHook (C:\localhost\csgo\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.finish (C:\localhost\csgo\node_modules\webpack\lib\Compilation.js:1253:28)
    at C:\localhost\csgo\node_modules\webpack\lib\Compiler.js:672:17
    at eval (eval at create (C:\localhost\csgo\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:11:1)
(node:3676) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async fu
nction without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled p
romise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (
rejection id: 2)
(node:3676) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not han
dled will terminate the Node.js process with a non-zero exit code.
[ event ] build page: /support
[ event ] build page: /support

```

**Comment by JoviDeCroock** [comment]
This issue contains no relevant information to even remotely derive the issue. What's your entry, ....

**Comment by MaxmaxmaximusGitHub** [comment]
I will try to create a separate repository and isolate the problem as much as possible

**Comment by JoviDeCroock** [comment]
Did this get fixed?
